// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHXHJKjHUl9EJA4U6tpm4hJ3qbPdn2es',
    appId: '1:982512768438:web:d025e8fd1d7d1e86f85d17',
    messagingSenderId: '982512768438',
    projectId: 'programalealtad-82d42',
    authDomain: 'programalealtad-82d42.firebaseapp.com',
    storageBucket: 'programalealtad-82d42.appspot.com',
    measurementId: 'G-59X9L8M0PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODS8uhdeEjy13yz05ggIT50RC7jVSNqs',
    appId: '1:982512768438:android:44f71fcfcf039a9ff85d17',
    messagingSenderId: '982512768438',
    projectId: 'programalealtad-82d42',
    storageBucket: 'programalealtad-82d42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTlHn2r-tUpccsRyMwHxCCfginOlWz7s',
    appId: '1:982512768438:ios:547bf00f07671904f85d17',
    messagingSenderId: '982512768438',
    projectId: 'programalealtad-82d42',
    storageBucket: 'programalealtad-82d42.appspot.com',
    iosBundleId: 'com.example.lealtadProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBTlHn2r-tUpccsRyMwHxCCfginOlWz7s',
    appId: '1:982512768438:ios:f14a7887d303b0bbf85d17',
    messagingSenderId: '982512768438',
    projectId: 'programalealtad-82d42',
    storageBucket: 'programalealtad-82d42.appspot.com',
    iosBundleId: 'com.example.lealtadProgram.RunnerTests',
  );
}
